# Generated by Django 4.0.1 on 2022-01-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PreOwnedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('reference_monthly_repayment', models.FloatField(blank=True, null=True, verbose_name='参考月供（¥）')),
                ('building_area', models.FloatField(verbose_name='建筑面积（m2）')),
                ('building_layout', models.CharField(max_length=20, verbose_name='户型,eg: 2-2-1')),
                ('floor_level', models.CharField(max_length=20, verbose_name='楼层位置')),
                ('age_of_building', models.DateField(verbose_name='建筑年代')),
                ('decoration_type', models.CharField(max_length=20, verbose_name='装修类型')),
                ('building_orientation', models.CharField(max_length=20, verbose_name='朝向')),
                ('building_structure', models.CharField(max_length=20, verbose_name='建筑结构')),
                ('building_type', models.CharField(max_length=20, verbose_name='建筑类型')),
                ('building_description', models.TextField(verbose_name='描述')),
                ('residential_quarter', models.CharField(max_length=50, verbose_name='小区')),
                ('address', models.CharField(max_length=255, verbose_name='地址')),
                ('affiliated_transportation', models.CharField(max_length=255, verbose_name='交通')),
                ('affiliated_facilities', models.CharField(max_length=255, verbose_name='配套设施')),
                ('published_at', models.DateTimeField(verbose_name='发布时间')),
                ('info_from', models.CharField(max_length=255, verbose_name='信息来源地址')),
                ('check_code', models.CharField(max_length=50, verbose_name='房源校验码')),
                ('related_sources', models.JSONField(default=[], verbose_name='小区其它在售房源')),
                ('exists_mortgage', models.BooleanField(default=False, verbose_name='存在抵押')),
                ('region', models.CharField(max_length=30, verbose_name='区域')),
                ('from_channel', models.CharField(max_length=20, verbose_name='登记来源')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
