# Generated by Django 4.0.1 on 2022-01-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preowneditem',
            name='related_sources',
            field=models.JSONField(default=list, verbose_name='小区其它在售房源'),
        ),
    ]
