# Generated by Django 4.0.1 on 2022-01-19 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_preowneditem_related_sources'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preowneditem',
            name='related_sources',
        ),
    ]
